import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import type { AppProps } from 'next/app';
import { getSession } from "@/actions";
import { redirect } from "next/navigation";
import ResponsiveAppBar from "../components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function fetchSession() {
  const session = await getSession();
  return session
}

export default async function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  const session = await fetchSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        {session.isLogin &&<ResponsiveAppBar/>}
        {children}
      </body>
    </html>
  );
}
