import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import type { AppProps } from 'next/app';
import { getSession } from "@/actions";

import ResponsiveAppBar from "../components/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  const session = getSession();
  console.log(session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ResponsiveAppBar/>
        {children}
      </body>
    </html>
  );
}
